# [START CICD / Step 1. Clone Repository]
steps:
# This step clones the hello-cloudbuild-env repository
- name: 'gcr.io/cloud-builders/git'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/caiottavares/gitops-env-repo.git && \
    cd gitops-env-repo && \
    git checkout production 

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'manifests/deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=caio-gke'
